export default [
  {
    id: 1,
    postedOn: "2024-12-01",
    title: "ios Developer",
    company: "Apple",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["SwiftUI", "UiKit", "Core Data"],
    job_link: "https://www.apple.com/careers/in/",
  },
  {
    id: 2,
    postedOn: "2024-12-01",
    title: "Frontend Developer",
    company: "Amazon",
    type: "Full Time",
    experience: "Fresher",
    location: "In-Office",
    skills: ["javascript", "NodeJs", "Tailwind CSS"],
    job_link: "https://www.amazon.jobs/en/",
  },
  {
    id: 3,
    postedOn: "2024-12-01",
    title: "Backend Developer",
    company: "Google",
    type: "Part Time",
    experience: "Senior",
    location: "Remote",
    skills: ["Python", "Django", "Rest API"],
    job_link: "https://careers.google.com/jobs/",
  },
  {
    id: 4,
    postedOn: "2024-12-01",
    title: "Full Stack Developer",
    company: "Microsoft",
    type: "Full Time",
    experience: "Fresher",
    location: "In-Office",
    skills: ["React", "NodeJs", "MongoDB"],
    job_link: "https://careers.microsoft.com/us/en/",
  },
  {
    id: 5,
    postedOn: "2024-12-01",
    title: "DevOps Engineer",
    company: "Facebook",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["Docker", "Kubernetes", "Jenkins"],
    job_link: "https://www.facebook.com/careers/",
  },
  {
    id: 6,
    postedOn: "2024-12-01",
    title: "Data Scientist",
    company: "Netflix",
    type: "Full Time",
    experience: "Senior",
    location: "Remote",
    skills: ["Python", "Machine Learning", "SQL"],
    job_link: "https://jobs.netflix.com/en/",
  },
  {
    id: 7,
    postedOn: "2024-12-01",
    title: "UI/UX Designer",
    company: "Adobe",
    type: "Full Time",
    experience: "Fresher",
    location: "In-Office",
    skills: ["Figma", "Adobe XD", "Photoshop"],
    job_link: "https://www.adobe.com/careers.html",
  },
  {
    id: 8,
    postedOn: "2024-12-01",
    title: "Cyber Security Analyst",
    company: "IBM",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["Ethical Hacking", "Firewall", "SIEM"],
    job_link: "https://www.ibm.com/in-en/employment/",
  },
  {
    id: 9,
    postedOn: "2024-12-01",
    title: "Android Developer",
    company: "Uber",
    type: "Full Time",
    experience: "Fresher",
    location: "In-Office",
    skills: ["Kotlin", "Java", "Android Studio"],
    job_link: "https://www.uber.com/global/en/careers/",
  },
  {
    id: 10,
    postedOn: "2024-12-01",
    title: "Developer Advocate",
    company: "Google",
    type: "Full Time",
    experience: "Senior",
    location: "Remote",
    skills: ["Go", "Kubernetes", "Cloud Computing"],
    job_link: "https://careers.google.com/",
  }
];
